name: Build Report PDF

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write # allow commit & push of the generated PDF

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout full history so we can commit back
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Python for plotting (headless)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # minimal common deps used by plotting scripts
            pip install matplotlib pandas numpy
          fi

      # 3) Generate data/plots for the report (headless matplotlib)
      - name: Generate report assets
        env:
          MPLBACKEND: Agg
        run: |
          set -e
          # if you have a clean rule, uncomment:
          # make clean || true
          make report
          # sanity check for the file your make target claims to produce:
          test -f report/times.dat || (echo "Missing report/times.dat" && exit 1)

      # 4) Compile LaTeX
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: report
          root_file: report.tex
          # Install extra system packages ONLY if your TeX needs them:
          # extra_system_packages: "gnuplot inkscape ghostscript"

      # 5) Upload PDF artifact
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: report/report.pdf

      # 6) Commit the generated PDF back to main
      - name: Commit PDF back to repo
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add report/report.pdf
          git commit -m "docs: auto-generate report and update PDF" || echo "No changes to commit"
          git push
